"""
ProjectInfo — fetches and displays project details from Jira and Zephyr Scale.

Usage:
    python -m test.project_info
    python -m test.project_info --id 12345
"""

import sys
import os
import argparse
import urllib.request
import urllib.error
import ssl
import json

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))

from main.config import AppConfig


class ProjectInfo:

    def __init__(self, project_id: str = ""):
        self._cfg         = AppConfig()
        self._ssl_ctx     = ssl.create_default_context()
        self._ssl_ctx.check_hostname = False
        self._ssl_ctx.verify_mode    = ssl.CERT_NONE

        # Parse project_id from zephyr_path at runtime — no need for project_id in config
        if project_id:
            self.project_id = project_id
        elif "projectId=" in self._cfg.zephyr_path:
            self.project_id = self._cfg.zephyr_path.split("projectId=")[-1].strip()
        else:
            print("[ERROR] Could not parse projectId from zephyr_path in config.properties.")
            sys.exit(1)

    def _jira_get(self, path: str) -> tuple:
        """Call Jira REST API (not Zephyr). Returns (status, parsed_json)."""
        url = f"{self._cfg.base_url}/rest/api/2{path}"
        req = urllib.request.Request(url, headers={
            "Authorization": f"Bearer {self._cfg.jira_token}",
            "Content-Type" : "application/json",
        })
        try:
            with urllib.request.urlopen(req, context=self._ssl_ctx) as r:
                return r.status, json.loads(r.read())
        except urllib.error.HTTPError as e:
            return e.code, {"error": e.read().decode()[:300]}

    def fetch_project(self) -> dict:
        status, data = self._jira_get(f"/project/{self.project_id}")
        return data if status == 200 else {}

    # — HTML report ————————————————————————————————————————————————————

    def generate_html(self, proj):
        from datetime import datetime
        run_time  = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        proj_key  = proj.get("key", "N/A")
        proj_name = proj.get("name", "N/A")
        proj_type = proj.get("projectTypeKey", "N/A")
        lead      = proj.get("lead", {})
        lead_name = f"{lead.get('displayName','N/A')} ({lead.get('name','')})"
        proj_url  = f"{self._cfg.base_url}{self._cfg.zephyr_path}"

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<title>Project Info — {proj_key}</title>
<style>
  body    {{ font-family: Segoe UI, Arial, sans-serif; background:#f4f6f9; margin:0; padding:20px; color:#333; }}
  h1      {{ background:#1a3c6e; color:#fff; padding:18px 24px; border-radius:6px; margin-bottom:14px; font-size:1.4em; }}
  .meta   {{ background:#fff; border:1px solid #dde3ed; border-radius:6px; padding:16px 24px; display:grid; grid-template-columns:160px 1fr; gap:8px 0; }}
  .meta .lbl{{ font-weight:600; color:#555; }}
  .meta a {{ color:#1a3c6e; }}
  .footer {{ text-align:center; color:#999; font-size:.8em; margin-top:20px; }}
</style>
</head>
<body>
<h1>&#128196; Jira / Zephyr Scale — Project Info</h1>

<div class="meta">
  <span class="lbl">Project Key</span>   <span>{proj_key}</span>
  <span class="lbl">Project Name</span>  <span>{proj_name}</span>
  <span class="lbl">Project Type</span>  <span>{proj_type}</span>
  <span class="lbl">Project Lead</span>  <span>{lead_name}</span>
  <span class="lbl">Project ID</span>    <span>{self.project_id}</span>
  <span class="lbl">Zephyr URL</span>    <span><a href="{proj_url}" target="_blank">{proj_url}</a></span>
  <span class="lbl">Generated</span>     <span>{run_time}</span>
</div>

<div class="footer">Generated by AITestCaseGen &bull; {run_time}</div>
</body></html>"""

        reports_dir = os.path.join(os.path.dirname(__file__), "..", "..", "reports")
        os.makedirs(reports_dir, exist_ok=True)
        out_path = os.path.join(reports_dir, "Project_Info_Report.html")
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(html)
        print(f"\n  📄  HTML report saved → {os.path.abspath(out_path)}")

    # — Run ————————————————————————————————————————————————————————————

    def run(self):
        print("=" * 65)
        print("  Jira / Zephyr Scale — Project Info")
        print("=" * 65)

        proj = self.fetch_project()
        if proj:
            lead = proj.get("lead", {})
            print(f"  Key  : {proj.get('key', 'N/A')}")
            print(f"  Name  : {proj.get('name', 'N/A')}")
            print(f"  Type  : {proj.get('projectTypeKey', 'N/A')}")
            print(f"  Lead  : {lead.get('displayName', 'N/A')} ({lead.get('name', '')})")
            print(f"  ID    : {self.project_id}")
            print(f"  URL   : {self._cfg.base_url}{self._cfg.zephyr_path}")
        else:
            print("  [WARN] Could not fetch project details.")
            print("=" * 65)
            return

        print("=" * 65)

        self.generate_html(proj)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Display Jira project details")
    parser.add_argument("--id", default="", help="Jira project ID (default: from config.properties)")
    args = parser.parse_args()
    ProjectInfo(project_id=args.id).run()
